// <auto-generated />
using System;
using InsurancePolicy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsurancePolicy.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241130130448_tables")]
    partial class tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerPolicy", b =>
                {
                    b.Property<Guid>("CustomersCustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PoliciesPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomersCustomerId", "PoliciesPolicyId");

                    b.HasIndex("PoliciesPolicyId");

                    b.ToTable("CustomerPolicy");
                });

            modelBuilder.Entity("InsurancePlanInsuranceScheme", b =>
                {
                    b.Property<Guid>("PlansPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchemesSchemeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlansPlanId", "SchemesSchemeId");

                    b.HasIndex("SchemesSchemeId");

                    b.ToTable("InsurancePlanInsuranceScheme");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Admin", b =>
                {
                    b.Property<Guid>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AdminFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdminLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdminPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Agent", b =>
                {
                    b.Property<Guid>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("AgentFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AgentLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("CommissionEarned")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AgentId");

                    b.HasIndex("UserId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("InsurancePolicy.Models.City", b =>
                {
                    b.Property<Guid>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityId = new Guid("c86eb902-4ff0-4b1e-8bc0-210f0b2fb6e6"),
                            CityName = "Visakhapatnam",
                            StateId = new Guid("ff790283-a7dd-4db6-9d17-5b287c4dc2ef")
                        },
                        new
                        {
                            CityId = new Guid("8a6d7ddc-82a1-4c86-9d04-7af231b32b70"),
                            CityName = "Vijayawada",
                            StateId = new Guid("ff790283-a7dd-4db6-9d17-5b287c4dc2ef")
                        },
                        new
                        {
                            CityId = new Guid("22e0da54-56cc-474e-acd1-b7e45d7a9d17"),
                            CityName = "Guntur",
                            StateId = new Guid("ff790283-a7dd-4db6-9d17-5b287c4dc2ef")
                        },
                        new
                        {
                            CityId = new Guid("2f5e0ef6-787d-423d-812c-29294cabb7e0"),
                            CityName = "Nellore",
                            StateId = new Guid("ff790283-a7dd-4db6-9d17-5b287c4dc2ef")
                        },
                        new
                        {
                            CityId = new Guid("bb600230-24d7-4b73-b75b-9adca6bf967d"),
                            CityName = "Tirupati",
                            StateId = new Guid("ff790283-a7dd-4db6-9d17-5b287c4dc2ef")
                        },
                        new
                        {
                            CityId = new Guid("8ea38249-311b-4cf9-aae5-cca601f15453"),
                            CityName = "Rajahmundry",
                            StateId = new Guid("ff790283-a7dd-4db6-9d17-5b287c4dc2ef")
                        },
                        new
                        {
                            CityId = new Guid("95e1f1db-49f7-45de-a393-c80b11e0927b"),
                            CityName = "Kakinada",
                            StateId = new Guid("ff790283-a7dd-4db6-9d17-5b287c4dc2ef")
                        },
                        new
                        {
                            CityId = new Guid("55cbb58c-4a54-4a8f-8fc9-179a92519a03"),
                            CityName = "Anantapur",
                            StateId = new Guid("ff790283-a7dd-4db6-9d17-5b287c4dc2ef")
                        },
                        new
                        {
                            CityId = new Guid("5725d33f-1db0-4d33-affb-5dd17a061d06"),
                            CityName = "Kadapa",
                            StateId = new Guid("ff790283-a7dd-4db6-9d17-5b287c4dc2ef")
                        },
                        new
                        {
                            CityId = new Guid("63406c16-5107-4937-838c-0343164f7db8"),
                            CityName = "Chittoor",
                            StateId = new Guid("ff790283-a7dd-4db6-9d17-5b287c4dc2ef")
                        },
                        new
                        {
                            CityId = new Guid("50cb5358-df58-4a81-a3f1-c67cb5704733"),
                            CityName = "Itanagar",
                            StateId = new Guid("ca59345f-670d-4536-8b5e-a71b581faad9")
                        },
                        new
                        {
                            CityId = new Guid("6d35f37a-dc9b-4324-9cd1-46ddea627eec"),
                            CityName = "Tawang",
                            StateId = new Guid("ca59345f-670d-4536-8b5e-a71b581faad9")
                        },
                        new
                        {
                            CityId = new Guid("f2f455e7-a950-4a68-bd5d-2f0031e8d8a2"),
                            CityName = "Ziro",
                            StateId = new Guid("ca59345f-670d-4536-8b5e-a71b581faad9")
                        },
                        new
                        {
                            CityId = new Guid("82faf966-84fd-4f7c-8923-758f389d4303"),
                            CityName = "Pasighat",
                            StateId = new Guid("ca59345f-670d-4536-8b5e-a71b581faad9")
                        },
                        new
                        {
                            CityId = new Guid("1b1a62a0-05bf-4646-a2df-bb807b71f8eb"),
                            CityName = "Bomdila",
                            StateId = new Guid("ca59345f-670d-4536-8b5e-a71b581faad9")
                        },
                        new
                        {
                            CityId = new Guid("97a11bc5-0cc7-4a8e-b810-b7a329780210"),
                            CityName = "Along",
                            StateId = new Guid("ca59345f-670d-4536-8b5e-a71b581faad9")
                        },
                        new
                        {
                            CityId = new Guid("42ac90dd-b3d1-4278-8e14-c4b4be3852cf"),
                            CityName = "Roing",
                            StateId = new Guid("ca59345f-670d-4536-8b5e-a71b581faad9")
                        },
                        new
                        {
                            CityId = new Guid("48ff1b62-fa31-4007-9cd2-2e633a013767"),
                            CityName = "Tezu",
                            StateId = new Guid("ca59345f-670d-4536-8b5e-a71b581faad9")
                        },
                        new
                        {
                            CityId = new Guid("47ff585e-b584-4242-9fdb-794cd8cc6df6"),
                            CityName = "Anini",
                            StateId = new Guid("ca59345f-670d-4536-8b5e-a71b581faad9")
                        },
                        new
                        {
                            CityId = new Guid("78d78612-1208-4e09-a008-07c4ee6fb49c"),
                            CityName = "Changlang",
                            StateId = new Guid("ca59345f-670d-4536-8b5e-a71b581faad9")
                        },
                        new
                        {
                            CityId = new Guid("d3ed691f-b26c-4d1d-889e-4c920ed54331"),
                            CityName = "Guwahati",
                            StateId = new Guid("76acffda-92b2-4fdc-b8cc-3eb78281e1fc")
                        },
                        new
                        {
                            CityId = new Guid("88441e25-f3d7-4c41-99b5-24cd8bc37809"),
                            CityName = "Silchar",
                            StateId = new Guid("76acffda-92b2-4fdc-b8cc-3eb78281e1fc")
                        },
                        new
                        {
                            CityId = new Guid("166e6a3c-d011-4fbf-a168-456060d1d114"),
                            CityName = "Dibrugarh",
                            StateId = new Guid("76acffda-92b2-4fdc-b8cc-3eb78281e1fc")
                        },
                        new
                        {
                            CityId = new Guid("715005a1-50ab-4eb6-a697-61a8be205d51"),
                            CityName = "Jorhat",
                            StateId = new Guid("76acffda-92b2-4fdc-b8cc-3eb78281e1fc")
                        },
                        new
                        {
                            CityId = new Guid("164f51e5-9a18-4dab-bf4e-6584358723cc"),
                            CityName = "Tezpur",
                            StateId = new Guid("76acffda-92b2-4fdc-b8cc-3eb78281e1fc")
                        },
                        new
                        {
                            CityId = new Guid("3383a922-269f-47f2-8615-033c8e3ae4fa"),
                            CityName = "Tinsukia",
                            StateId = new Guid("76acffda-92b2-4fdc-b8cc-3eb78281e1fc")
                        },
                        new
                        {
                            CityId = new Guid("77edad38-370e-46f5-b725-2162ee4afdcc"),
                            CityName = "Nagaon",
                            StateId = new Guid("76acffda-92b2-4fdc-b8cc-3eb78281e1fc")
                        },
                        new
                        {
                            CityId = new Guid("d9622704-57b0-40a6-a75d-1cee06f28e98"),
                            CityName = "Barpeta",
                            StateId = new Guid("76acffda-92b2-4fdc-b8cc-3eb78281e1fc")
                        },
                        new
                        {
                            CityId = new Guid("51aedcee-992c-46bc-a1ff-56b46a3131ad"),
                            CityName = "Goalpara",
                            StateId = new Guid("76acffda-92b2-4fdc-b8cc-3eb78281e1fc")
                        },
                        new
                        {
                            CityId = new Guid("2dba4fc3-ccb2-40bb-a1a4-76d5242294db"),
                            CityName = "Bongaigaon",
                            StateId = new Guid("76acffda-92b2-4fdc-b8cc-3eb78281e1fc")
                        },
                        new
                        {
                            CityId = new Guid("f5b30fa8-d862-43ba-9b36-40ed9c779871"),
                            CityName = "Patna",
                            StateId = new Guid("700b8d6b-ace2-4d89-8eb6-35ae1009a7f3")
                        },
                        new
                        {
                            CityId = new Guid("cec91794-e9af-4a1a-820b-c7e6a77401f6"),
                            CityName = "Gaya",
                            StateId = new Guid("700b8d6b-ace2-4d89-8eb6-35ae1009a7f3")
                        },
                        new
                        {
                            CityId = new Guid("5c905c0a-f032-45e7-a4ea-6460fb610baf"),
                            CityName = "Bhagalpur",
                            StateId = new Guid("700b8d6b-ace2-4d89-8eb6-35ae1009a7f3")
                        },
                        new
                        {
                            CityId = new Guid("561d3741-4076-475f-802b-fb70c0e8dd1e"),
                            CityName = "Muzaffarpur",
                            StateId = new Guid("700b8d6b-ace2-4d89-8eb6-35ae1009a7f3")
                        },
                        new
                        {
                            CityId = new Guid("1f99400b-2eea-48d1-b471-40ea7d1272f3"),
                            CityName = "Darbhanga",
                            StateId = new Guid("700b8d6b-ace2-4d89-8eb6-35ae1009a7f3")
                        },
                        new
                        {
                            CityId = new Guid("937ad25b-86e2-43a2-9222-3f9ba46e0252"),
                            CityName = "Purnia",
                            StateId = new Guid("700b8d6b-ace2-4d89-8eb6-35ae1009a7f3")
                        },
                        new
                        {
                            CityId = new Guid("a642360e-6955-49e2-be7d-890127bc59cf"),
                            CityName = "Hajipur",
                            StateId = new Guid("700b8d6b-ace2-4d89-8eb6-35ae1009a7f3")
                        },
                        new
                        {
                            CityId = new Guid("9081cf7e-d3be-4128-9e6e-e021b264dbec"),
                            CityName = "Ara",
                            StateId = new Guid("700b8d6b-ace2-4d89-8eb6-35ae1009a7f3")
                        },
                        new
                        {
                            CityId = new Guid("6d429c9b-f230-4c63-8d28-c178ee7ad359"),
                            CityName = "Sasaram",
                            StateId = new Guid("700b8d6b-ace2-4d89-8eb6-35ae1009a7f3")
                        },
                        new
                        {
                            CityId = new Guid("a9f051b1-0182-43db-8513-74db9f549bf1"),
                            CityName = "Begusarai",
                            StateId = new Guid("700b8d6b-ace2-4d89-8eb6-35ae1009a7f3")
                        },
                        new
                        {
                            CityId = new Guid("8a17e321-c64e-4301-9fbd-68c4199ce8ea"),
                            CityName = "Raipur",
                            StateId = new Guid("45d6dac4-356d-412c-9290-720ac52cec06")
                        },
                        new
                        {
                            CityId = new Guid("2bfafb6c-30e7-41eb-bb98-5bd96388dd8a"),
                            CityName = "Bilaspur",
                            StateId = new Guid("45d6dac4-356d-412c-9290-720ac52cec06")
                        },
                        new
                        {
                            CityId = new Guid("81190233-562b-4973-a748-0d9f476debf0"),
                            CityName = "Korba",
                            StateId = new Guid("45d6dac4-356d-412c-9290-720ac52cec06")
                        },
                        new
                        {
                            CityId = new Guid("015f3947-7eb6-4e03-ae80-9c0e2500ba2b"),
                            CityName = "Durg",
                            StateId = new Guid("45d6dac4-356d-412c-9290-720ac52cec06")
                        },
                        new
                        {
                            CityId = new Guid("44e93a42-4b3e-45b7-bf49-4fe049c97e10"),
                            CityName = "Bhilai",
                            StateId = new Guid("45d6dac4-356d-412c-9290-720ac52cec06")
                        },
                        new
                        {
                            CityId = new Guid("6e348b50-c3f7-498a-b9b1-2b90b21a21b3"),
                            CityName = "Jagdalpur",
                            StateId = new Guid("45d6dac4-356d-412c-9290-720ac52cec06")
                        },
                        new
                        {
                            CityId = new Guid("73653f61-05f4-4352-9e53-1213c6cd6c09"),
                            CityName = "Rajnandgaon",
                            StateId = new Guid("45d6dac4-356d-412c-9290-720ac52cec06")
                        },
                        new
                        {
                            CityId = new Guid("b8cc061a-5200-41f4-a094-a31c37dad582"),
                            CityName = "Raigarh",
                            StateId = new Guid("45d6dac4-356d-412c-9290-720ac52cec06")
                        },
                        new
                        {
                            CityId = new Guid("e6d056f5-6003-4c6a-a703-86537adc91a1"),
                            CityName = "Ambikapur",
                            StateId = new Guid("45d6dac4-356d-412c-9290-720ac52cec06")
                        },
                        new
                        {
                            CityId = new Guid("d3b9c5d4-9bd2-45d5-bbf3-48650ffca62d"),
                            CityName = "Mahasamund",
                            StateId = new Guid("45d6dac4-356d-412c-9290-720ac52cec06")
                        },
                        new
                        {
                            CityId = new Guid("5b2963a6-9e06-4bb6-8bf7-920c8ffba15f"),
                            CityName = "Panaji",
                            StateId = new Guid("aa9dfba4-af52-4b09-b3ee-bcd036bdc245")
                        },
                        new
                        {
                            CityId = new Guid("5b491cfa-35f0-4173-a104-4b3fed4e68e6"),
                            CityName = "Margao",
                            StateId = new Guid("aa9dfba4-af52-4b09-b3ee-bcd036bdc245")
                        },
                        new
                        {
                            CityId = new Guid("b657ac7c-dabf-409f-ad8e-d93be903a8c9"),
                            CityName = "Vasco da Gama",
                            StateId = new Guid("aa9dfba4-af52-4b09-b3ee-bcd036bdc245")
                        },
                        new
                        {
                            CityId = new Guid("fcc583eb-6507-4638-a79e-e1e0a8914ca3"),
                            CityName = "Mapusa",
                            StateId = new Guid("aa9dfba4-af52-4b09-b3ee-bcd036bdc245")
                        },
                        new
                        {
                            CityId = new Guid("9a95dcc4-9b04-4bd0-b0e2-67fdca80322e"),
                            CityName = "Ponda",
                            StateId = new Guid("aa9dfba4-af52-4b09-b3ee-bcd036bdc245")
                        },
                        new
                        {
                            CityId = new Guid("8b914b51-888b-4a3c-b382-33b2e783d5b7"),
                            CityName = "Calangute",
                            StateId = new Guid("aa9dfba4-af52-4b09-b3ee-bcd036bdc245")
                        },
                        new
                        {
                            CityId = new Guid("05bb0ba1-3c46-4996-b7c0-34c37a2d245c"),
                            CityName = "Bicholim",
                            StateId = new Guid("aa9dfba4-af52-4b09-b3ee-bcd036bdc245")
                        },
                        new
                        {
                            CityId = new Guid("b5497500-dcca-42ce-b11f-e1ab88f41eb3"),
                            CityName = "Porvorim",
                            StateId = new Guid("aa9dfba4-af52-4b09-b3ee-bcd036bdc245")
                        },
                        new
                        {
                            CityId = new Guid("63c0fedb-87c8-4b7c-8ea9-9ae00dc98bc9"),
                            CityName = "Canacona",
                            StateId = new Guid("aa9dfba4-af52-4b09-b3ee-bcd036bdc245")
                        },
                        new
                        {
                            CityId = new Guid("b5f9d4ae-cdfe-4beb-b563-64113e489bf3"),
                            CityName = "Dona Paula",
                            StateId = new Guid("aa9dfba4-af52-4b09-b3ee-bcd036bdc245")
                        },
                        new
                        {
                            CityId = new Guid("313defb6-f8da-4cf8-a60c-5598417bd618"),
                            CityName = "Ahmedabad",
                            StateId = new Guid("60e8c0fe-f916-4917-94ad-5a486d5703a4")
                        },
                        new
                        {
                            CityId = new Guid("cdf7a5ed-d972-42ea-aca5-5ed1790294d4"),
                            CityName = "Surat",
                            StateId = new Guid("60e8c0fe-f916-4917-94ad-5a486d5703a4")
                        },
                        new
                        {
                            CityId = new Guid("afeb9590-d7bf-49a2-b9c2-b11c69490198"),
                            CityName = "Vadodara",
                            StateId = new Guid("60e8c0fe-f916-4917-94ad-5a486d5703a4")
                        },
                        new
                        {
                            CityId = new Guid("8a64565d-3b76-42e4-9bce-c1b372bd2b6d"),
                            CityName = "Rajkot",
                            StateId = new Guid("60e8c0fe-f916-4917-94ad-5a486d5703a4")
                        },
                        new
                        {
                            CityId = new Guid("25b654be-8f1a-4a39-876e-ac2a5854833a"),
                            CityName = "Bhavnagar",
                            StateId = new Guid("60e8c0fe-f916-4917-94ad-5a486d5703a4")
                        },
                        new
                        {
                            CityId = new Guid("f5dd889b-2d72-4a57-bddb-d76dc55fd4f8"),
                            CityName = "Jamnagar",
                            StateId = new Guid("60e8c0fe-f916-4917-94ad-5a486d5703a4")
                        },
                        new
                        {
                            CityId = new Guid("2134dd8c-3d41-4098-8ad1-09eb6a813027"),
                            CityName = "Gandhinagar",
                            StateId = new Guid("60e8c0fe-f916-4917-94ad-5a486d5703a4")
                        },
                        new
                        {
                            CityId = new Guid("3bdd4d4a-2cd4-43c3-97ca-95fe8c6f6b1b"),
                            CityName = "Anand",
                            StateId = new Guid("60e8c0fe-f916-4917-94ad-5a486d5703a4")
                        },
                        new
                        {
                            CityId = new Guid("e7d78951-4de6-4379-97c0-09e608b8bf51"),
                            CityName = "Navsari",
                            StateId = new Guid("60e8c0fe-f916-4917-94ad-5a486d5703a4")
                        },
                        new
                        {
                            CityId = new Guid("bbc93f2b-9b1e-4c8b-9b4f-163ebf49521e"),
                            CityName = "Mehsana",
                            StateId = new Guid("60e8c0fe-f916-4917-94ad-5a486d5703a4")
                        },
                        new
                        {
                            CityId = new Guid("265d659f-19eb-466a-a4b0-18f1aa4ab5a4"),
                            CityName = "Gurgaon",
                            StateId = new Guid("ad61f74f-efa5-41f5-bb98-5ca0d89778c8")
                        },
                        new
                        {
                            CityId = new Guid("37e23f90-5ded-4ec2-9968-3c7324d30eae"),
                            CityName = "Faridabad",
                            StateId = new Guid("ad61f74f-efa5-41f5-bb98-5ca0d89778c8")
                        },
                        new
                        {
                            CityId = new Guid("39c668b8-8c37-45b0-9311-67414cf7a61c"),
                            CityName = "Panipat",
                            StateId = new Guid("ad61f74f-efa5-41f5-bb98-5ca0d89778c8")
                        },
                        new
                        {
                            CityId = new Guid("5677c3a5-6778-443d-9120-be42bd573c6b"),
                            CityName = "Ambala",
                            StateId = new Guid("ad61f74f-efa5-41f5-bb98-5ca0d89778c8")
                        },
                        new
                        {
                            CityId = new Guid("13f9ace7-65b0-4de0-8049-90f42f2b3e85"),
                            CityName = "Hisar",
                            StateId = new Guid("ad61f74f-efa5-41f5-bb98-5ca0d89778c8")
                        },
                        new
                        {
                            CityId = new Guid("e5eac272-b008-4feb-a7de-d44f5b3ba373"),
                            CityName = "Rohtak",
                            StateId = new Guid("ad61f74f-efa5-41f5-bb98-5ca0d89778c8")
                        },
                        new
                        {
                            CityId = new Guid("b7547999-70d8-443c-9f05-51b5b995550b"),
                            CityName = "Karnal",
                            StateId = new Guid("ad61f74f-efa5-41f5-bb98-5ca0d89778c8")
                        },
                        new
                        {
                            CityId = new Guid("4f3c5c3d-d936-419d-976d-159f81815e26"),
                            CityName = "Yamunanagar",
                            StateId = new Guid("ad61f74f-efa5-41f5-bb98-5ca0d89778c8")
                        },
                        new
                        {
                            CityId = new Guid("7fe362e6-7e87-4a06-87ae-536975cc1612"),
                            CityName = "Sirsa",
                            StateId = new Guid("ad61f74f-efa5-41f5-bb98-5ca0d89778c8")
                        },
                        new
                        {
                            CityId = new Guid("db0cf04b-bfed-4ae8-8cea-de55997dc982"),
                            CityName = "Bhiwani",
                            StateId = new Guid("ad61f74f-efa5-41f5-bb98-5ca0d89778c8")
                        },
                        new
                        {
                            CityId = new Guid("f1f77d92-5f11-444a-a917-e1a31272804d"),
                            CityName = "Shimla",
                            StateId = new Guid("ef4f21a3-110b-4826-8e48-4cebfea255b2")
                        },
                        new
                        {
                            CityId = new Guid("5764ccbb-64c6-46ae-9b46-8904c5ecfb29"),
                            CityName = "Manali",
                            StateId = new Guid("ef4f21a3-110b-4826-8e48-4cebfea255b2")
                        },
                        new
                        {
                            CityId = new Guid("f3194163-b618-4d37-8323-e9cacde6643b"),
                            CityName = "Dharamshala",
                            StateId = new Guid("ef4f21a3-110b-4826-8e48-4cebfea255b2")
                        },
                        new
                        {
                            CityId = new Guid("7049f229-1e8b-4733-a8df-ef396bd5ae4c"),
                            CityName = "Kullu",
                            StateId = new Guid("ef4f21a3-110b-4826-8e48-4cebfea255b2")
                        },
                        new
                        {
                            CityId = new Guid("44f8e24c-7d69-4e84-9ce9-17a63cd548a9"),
                            CityName = "Solan",
                            StateId = new Guid("ef4f21a3-110b-4826-8e48-4cebfea255b2")
                        },
                        new
                        {
                            CityId = new Guid("aef4986f-2669-4352-b0b4-1e6e58c20b53"),
                            CityName = "Mandi",
                            StateId = new Guid("ef4f21a3-110b-4826-8e48-4cebfea255b2")
                        },
                        new
                        {
                            CityId = new Guid("2bfad885-33e0-4337-9de0-405165f9d82b"),
                            CityName = "Chamba",
                            StateId = new Guid("ef4f21a3-110b-4826-8e48-4cebfea255b2")
                        },
                        new
                        {
                            CityId = new Guid("60a772a5-bdeb-4ea7-b67f-851c20f5d45b"),
                            CityName = "Bilaspur",
                            StateId = new Guid("ef4f21a3-110b-4826-8e48-4cebfea255b2")
                        },
                        new
                        {
                            CityId = new Guid("72e2dc0a-49ad-4fa0-98f6-9c661492433d"),
                            CityName = "Hamirpur",
                            StateId = new Guid("ef4f21a3-110b-4826-8e48-4cebfea255b2")
                        },
                        new
                        {
                            CityId = new Guid("d0a11de5-c071-4aae-8262-4f095dfb1c55"),
                            CityName = "Nahan",
                            StateId = new Guid("ef4f21a3-110b-4826-8e48-4cebfea255b2")
                        },
                        new
                        {
                            CityId = new Guid("0bf45726-f8e1-434b-9b95-bdf0b6fcb268"),
                            CityName = "Ranchi",
                            StateId = new Guid("8c9c47ad-b2ed-46fc-abe7-16948ab15a0a")
                        },
                        new
                        {
                            CityId = new Guid("7ff436bc-c94a-4e67-8136-b6b3388349a6"),
                            CityName = "Jamshedpur",
                            StateId = new Guid("8c9c47ad-b2ed-46fc-abe7-16948ab15a0a")
                        },
                        new
                        {
                            CityId = new Guid("11df9f07-9270-4160-a99d-b044d1405b83"),
                            CityName = "Dhanbad",
                            StateId = new Guid("8c9c47ad-b2ed-46fc-abe7-16948ab15a0a")
                        },
                        new
                        {
                            CityId = new Guid("4b976794-e5bc-448b-adb3-b3a6bac1d90c"),
                            CityName = "Bokaro",
                            StateId = new Guid("8c9c47ad-b2ed-46fc-abe7-16948ab15a0a")
                        },
                        new
                        {
                            CityId = new Guid("ffb5275b-a6e4-4d1a-b668-69c22c724785"),
                            CityName = "Hazaribagh",
                            StateId = new Guid("8c9c47ad-b2ed-46fc-abe7-16948ab15a0a")
                        },
                        new
                        {
                            CityId = new Guid("4cea5502-64d8-4793-87a8-ca80b94da5ad"),
                            CityName = "Deoghar",
                            StateId = new Guid("8c9c47ad-b2ed-46fc-abe7-16948ab15a0a")
                        },
                        new
                        {
                            CityId = new Guid("5e83e319-5ce0-4ca0-9b3b-1a49cc121563"),
                            CityName = "Giridih",
                            StateId = new Guid("8c9c47ad-b2ed-46fc-abe7-16948ab15a0a")
                        },
                        new
                        {
                            CityId = new Guid("06da1111-77ae-49b2-a515-ca5244fece56"),
                            CityName = "Ramgarh",
                            StateId = new Guid("8c9c47ad-b2ed-46fc-abe7-16948ab15a0a")
                        },
                        new
                        {
                            CityId = new Guid("a624f0d3-2d73-49db-8d4a-1c411d7260d1"),
                            CityName = "Godda",
                            StateId = new Guid("8c9c47ad-b2ed-46fc-abe7-16948ab15a0a")
                        },
                        new
                        {
                            CityId = new Guid("58cc1ca0-7d16-4b03-b772-dc851a1a29ad"),
                            CityName = "Pakur",
                            StateId = new Guid("8c9c47ad-b2ed-46fc-abe7-16948ab15a0a")
                        },
                        new
                        {
                            CityId = new Guid("12054b14-7203-4c81-946e-379fb0c27cff"),
                            CityName = "Bangalore",
                            StateId = new Guid("4df48888-8202-446b-a3d9-d51174a53738")
                        },
                        new
                        {
                            CityId = new Guid("9697a9e5-ff6d-457a-b48e-accfba644e43"),
                            CityName = "Mysore",
                            StateId = new Guid("4df48888-8202-446b-a3d9-d51174a53738")
                        },
                        new
                        {
                            CityId = new Guid("4930ddb2-2999-4040-a7a7-78d7bc32a538"),
                            CityName = "Mangalore",
                            StateId = new Guid("4df48888-8202-446b-a3d9-d51174a53738")
                        },
                        new
                        {
                            CityId = new Guid("5c12b85b-95ad-4092-bac7-a0b9af05d3a8"),
                            CityName = "Hubli",
                            StateId = new Guid("4df48888-8202-446b-a3d9-d51174a53738")
                        },
                        new
                        {
                            CityId = new Guid("541c0bc6-92d6-4782-90c6-bd1f6295b28a"),
                            CityName = "Belgaum",
                            StateId = new Guid("4df48888-8202-446b-a3d9-d51174a53738")
                        },
                        new
                        {
                            CityId = new Guid("209c0ca2-b526-4aca-8a29-e8dd79a04ed3"),
                            CityName = "Davanagere",
                            StateId = new Guid("4df48888-8202-446b-a3d9-d51174a53738")
                        },
                        new
                        {
                            CityId = new Guid("439f1caf-39e8-4fac-bae3-8d71f2f9d44e"),
                            CityName = "Bellary",
                            StateId = new Guid("4df48888-8202-446b-a3d9-d51174a53738")
                        },
                        new
                        {
                            CityId = new Guid("cce49c60-55e9-4555-8907-2f602d2bc2e7"),
                            CityName = "Bijapur",
                            StateId = new Guid("4df48888-8202-446b-a3d9-d51174a53738")
                        },
                        new
                        {
                            CityId = new Guid("079ac9d4-4b43-4eb2-9b9b-e141b645dcee"),
                            CityName = "Shimoga",
                            StateId = new Guid("4df48888-8202-446b-a3d9-d51174a53738")
                        },
                        new
                        {
                            CityId = new Guid("0a737c86-ce36-443f-b256-85d0a79b8b82"),
                            CityName = "Udupi",
                            StateId = new Guid("4df48888-8202-446b-a3d9-d51174a53738")
                        },
                        new
                        {
                            CityId = new Guid("e815cca0-ac2a-4db3-9f69-c8e7305a430c"),
                            CityName = "Thiruvananthapuram",
                            StateId = new Guid("6cd8dcf5-c85c-4fd7-bba8-fc28fcc4852d")
                        },
                        new
                        {
                            CityId = new Guid("9e72b498-b971-46a4-a706-03df9cc1dabf"),
                            CityName = "Kochi",
                            StateId = new Guid("6cd8dcf5-c85c-4fd7-bba8-fc28fcc4852d")
                        },
                        new
                        {
                            CityId = new Guid("8f328036-a828-4d1e-b7a2-73fd2c492359"),
                            CityName = "Kozhikode",
                            StateId = new Guid("6cd8dcf5-c85c-4fd7-bba8-fc28fcc4852d")
                        },
                        new
                        {
                            CityId = new Guid("a43243f7-9c2b-4887-8d39-35db6ba6a04a"),
                            CityName = "Thrissur",
                            StateId = new Guid("6cd8dcf5-c85c-4fd7-bba8-fc28fcc4852d")
                        },
                        new
                        {
                            CityId = new Guid("9eb5e508-dbc2-49e4-8c8f-da085b39937f"),
                            CityName = "Kollam",
                            StateId = new Guid("6cd8dcf5-c85c-4fd7-bba8-fc28fcc4852d")
                        },
                        new
                        {
                            CityId = new Guid("ff0de4f9-ad31-42eb-9e2e-0c654a0d910c"),
                            CityName = "Alappuzha",
                            StateId = new Guid("6cd8dcf5-c85c-4fd7-bba8-fc28fcc4852d")
                        },
                        new
                        {
                            CityId = new Guid("d05e01ef-7c45-49cd-89cd-75327fb61f3b"),
                            CityName = "Kannur",
                            StateId = new Guid("6cd8dcf5-c85c-4fd7-bba8-fc28fcc4852d")
                        },
                        new
                        {
                            CityId = new Guid("384f8016-925d-4793-b7a7-510ae1259041"),
                            CityName = "Palakkad",
                            StateId = new Guid("6cd8dcf5-c85c-4fd7-bba8-fc28fcc4852d")
                        },
                        new
                        {
                            CityId = new Guid("44f2425d-e26b-44a5-81bf-a8bfa1182ad4"),
                            CityName = "Malappuram",
                            StateId = new Guid("6cd8dcf5-c85c-4fd7-bba8-fc28fcc4852d")
                        },
                        new
                        {
                            CityId = new Guid("e99b73ad-cdd5-491e-ba8f-ba522603fe90"),
                            CityName = "Idukki",
                            StateId = new Guid("6cd8dcf5-c85c-4fd7-bba8-fc28fcc4852d")
                        },
                        new
                        {
                            CityId = new Guid("cc32820d-d629-423b-8e11-c6e73ce578b8"),
                            CityName = "Bhopal",
                            StateId = new Guid("d8bfef23-508d-4c5b-acc1-b4388b39bc7b")
                        },
                        new
                        {
                            CityId = new Guid("5b7b563f-0f8b-4a96-8c46-b039877a78bd"),
                            CityName = "Indore",
                            StateId = new Guid("d8bfef23-508d-4c5b-acc1-b4388b39bc7b")
                        },
                        new
                        {
                            CityId = new Guid("ada8b6d0-c702-4787-b902-ae4b4efd0f69"),
                            CityName = "Gwalior",
                            StateId = new Guid("d8bfef23-508d-4c5b-acc1-b4388b39bc7b")
                        },
                        new
                        {
                            CityId = new Guid("9698d6f7-ccba-4ad1-801a-657ec7fdfe2c"),
                            CityName = "Jabalpur",
                            StateId = new Guid("d8bfef23-508d-4c5b-acc1-b4388b39bc7b")
                        },
                        new
                        {
                            CityId = new Guid("277ffcb2-ef9e-4446-b224-4757c65dbf58"),
                            CityName = "Ujjain",
                            StateId = new Guid("d8bfef23-508d-4c5b-acc1-b4388b39bc7b")
                        },
                        new
                        {
                            CityId = new Guid("cc21a8b3-2dac-425a-b4c6-cd388b7d7cb5"),
                            CityName = "Sagar",
                            StateId = new Guid("d8bfef23-508d-4c5b-acc1-b4388b39bc7b")
                        },
                        new
                        {
                            CityId = new Guid("2a880119-3207-444b-8ed3-f1329b50469c"),
                            CityName = "Rewa",
                            StateId = new Guid("d8bfef23-508d-4c5b-acc1-b4388b39bc7b")
                        },
                        new
                        {
                            CityId = new Guid("ccc34628-93a1-4e76-bf64-63c91a2eac61"),
                            CityName = "Ratlam",
                            StateId = new Guid("d8bfef23-508d-4c5b-acc1-b4388b39bc7b")
                        },
                        new
                        {
                            CityId = new Guid("974c7b59-66b4-4885-93aa-3d2bbf2cef29"),
                            CityName = "Satna",
                            StateId = new Guid("d8bfef23-508d-4c5b-acc1-b4388b39bc7b")
                        },
                        new
                        {
                            CityId = new Guid("ee262744-595c-4bde-a21b-61a4e3a47816"),
                            CityName = "Chhindwara",
                            StateId = new Guid("d8bfef23-508d-4c5b-acc1-b4388b39bc7b")
                        },
                        new
                        {
                            CityId = new Guid("7e33ac8e-f4e3-4a59-9d56-7e4656807e91"),
                            CityName = "Mumbai",
                            StateId = new Guid("e12f6cad-eed1-4d26-a17c-737afe19c94f")
                        },
                        new
                        {
                            CityId = new Guid("30ba9dc1-ff1b-4f2d-a4cf-143c13d5f061"),
                            CityName = "Pune",
                            StateId = new Guid("e12f6cad-eed1-4d26-a17c-737afe19c94f")
                        },
                        new
                        {
                            CityId = new Guid("58f352fb-e0a9-4c72-b956-47f3b2be77f1"),
                            CityName = "Nagpur",
                            StateId = new Guid("e12f6cad-eed1-4d26-a17c-737afe19c94f")
                        },
                        new
                        {
                            CityId = new Guid("2e9650eb-d504-48f5-9e22-c9a0a09d8e29"),
                            CityName = "Nashik",
                            StateId = new Guid("e12f6cad-eed1-4d26-a17c-737afe19c94f")
                        },
                        new
                        {
                            CityId = new Guid("57846f42-ee05-40e9-a6c9-bbeeca45c399"),
                            CityName = "Thane",
                            StateId = new Guid("e12f6cad-eed1-4d26-a17c-737afe19c94f")
                        },
                        new
                        {
                            CityId = new Guid("c277b464-b4b3-4e42-9833-55973d143167"),
                            CityName = "Aurangabad",
                            StateId = new Guid("e12f6cad-eed1-4d26-a17c-737afe19c94f")
                        },
                        new
                        {
                            CityId = new Guid("6928fa67-9ef0-4aaa-bce4-85496d69080c"),
                            CityName = "Solapur",
                            StateId = new Guid("e12f6cad-eed1-4d26-a17c-737afe19c94f")
                        },
                        new
                        {
                            CityId = new Guid("43020f0f-06ab-47ef-b5c1-dbc5be9b7301"),
                            CityName = "Kolhapur",
                            StateId = new Guid("e12f6cad-eed1-4d26-a17c-737afe19c94f")
                        },
                        new
                        {
                            CityId = new Guid("ebb79057-3776-41ef-8ba1-8e87d7725d31"),
                            CityName = "Amravati",
                            StateId = new Guid("e12f6cad-eed1-4d26-a17c-737afe19c94f")
                        },
                        new
                        {
                            CityId = new Guid("41bfb161-8a5b-4355-abf9-631a767b9a9a"),
                            CityName = "Sangli",
                            StateId = new Guid("e12f6cad-eed1-4d26-a17c-737afe19c94f")
                        },
                        new
                        {
                            CityId = new Guid("b153c17d-560a-4939-9936-87b0c2b9a849"),
                            CityName = "Jaipur",
                            StateId = new Guid("4f5b2aa8-9cc6-4046-bc15-c808010b52d8")
                        },
                        new
                        {
                            CityId = new Guid("4fa9b5fc-94f0-4a7f-a4ec-85a403ce074d"),
                            CityName = "Jodhpur",
                            StateId = new Guid("4f5b2aa8-9cc6-4046-bc15-c808010b52d8")
                        },
                        new
                        {
                            CityId = new Guid("58a1f29b-62e7-47b7-8c44-79329c436533"),
                            CityName = "Udaipur",
                            StateId = new Guid("4f5b2aa8-9cc6-4046-bc15-c808010b52d8")
                        },
                        new
                        {
                            CityId = new Guid("b67826bf-6916-4afd-b1d4-08727d195858"),
                            CityName = "Kota",
                            StateId = new Guid("4f5b2aa8-9cc6-4046-bc15-c808010b52d8")
                        },
                        new
                        {
                            CityId = new Guid("8bc0b009-842a-45f1-98ea-fd490da12be1"),
                            CityName = "Ajmer",
                            StateId = new Guid("4f5b2aa8-9cc6-4046-bc15-c808010b52d8")
                        },
                        new
                        {
                            CityId = new Guid("1f29941d-1968-41e4-b2fc-ddf146f80f19"),
                            CityName = "Bikaner",
                            StateId = new Guid("4f5b2aa8-9cc6-4046-bc15-c808010b52d8")
                        },
                        new
                        {
                            CityId = new Guid("84c06538-7f67-4e1b-a304-77de2860ecc1"),
                            CityName = "Alwar",
                            StateId = new Guid("4f5b2aa8-9cc6-4046-bc15-c808010b52d8")
                        },
                        new
                        {
                            CityId = new Guid("88bcbb43-9457-4998-a63d-4645fc2b35d9"),
                            CityName = "Bharatpur",
                            StateId = new Guid("4f5b2aa8-9cc6-4046-bc15-c808010b52d8")
                        },
                        new
                        {
                            CityId = new Guid("d3bd4dbf-b4c9-4302-832f-5f8c9c80ccc2"),
                            CityName = "Jaisalmer",
                            StateId = new Guid("4f5b2aa8-9cc6-4046-bc15-c808010b52d8")
                        },
                        new
                        {
                            CityId = new Guid("d468cbf5-be9b-45a0-b26c-902997994781"),
                            CityName = "Sikar",
                            StateId = new Guid("4f5b2aa8-9cc6-4046-bc15-c808010b52d8")
                        },
                        new
                        {
                            CityId = new Guid("7c6eb7c5-5539-482a-9fb5-1814921693dc"),
                            CityName = "Chennai",
                            StateId = new Guid("fab9319b-19ce-4029-a86e-7517eecba3dd")
                        },
                        new
                        {
                            CityId = new Guid("06e71347-9b53-4083-aaed-8462c98d1259"),
                            CityName = "Coimbatore",
                            StateId = new Guid("fab9319b-19ce-4029-a86e-7517eecba3dd")
                        },
                        new
                        {
                            CityId = new Guid("1e518281-57fc-4cee-84da-351077b4ee5d"),
                            CityName = "Madurai",
                            StateId = new Guid("fab9319b-19ce-4029-a86e-7517eecba3dd")
                        },
                        new
                        {
                            CityId = new Guid("f172ba6c-8af4-4954-af70-9de0f2df6537"),
                            CityName = "Tiruchirappalli",
                            StateId = new Guid("fab9319b-19ce-4029-a86e-7517eecba3dd")
                        },
                        new
                        {
                            CityId = new Guid("3047dd43-e676-47c6-bed6-ab1e949ddac0"),
                            CityName = "Salem",
                            StateId = new Guid("fab9319b-19ce-4029-a86e-7517eecba3dd")
                        },
                        new
                        {
                            CityId = new Guid("015f1e4e-6aeb-4223-8665-bd973c7d14a4"),
                            CityName = "Tirunelveli",
                            StateId = new Guid("fab9319b-19ce-4029-a86e-7517eecba3dd")
                        },
                        new
                        {
                            CityId = new Guid("76b7f01d-9705-4994-ba2a-d0ef87660b59"),
                            CityName = "Erode",
                            StateId = new Guid("fab9319b-19ce-4029-a86e-7517eecba3dd")
                        },
                        new
                        {
                            CityId = new Guid("67413103-fcca-4ee0-9253-ca5350c02b61"),
                            CityName = "Vellore",
                            StateId = new Guid("fab9319b-19ce-4029-a86e-7517eecba3dd")
                        },
                        new
                        {
                            CityId = new Guid("5ebd3b8f-fc6d-44a5-ac3e-bf4dc082ea6c"),
                            CityName = "Thoothukudi",
                            StateId = new Guid("fab9319b-19ce-4029-a86e-7517eecba3dd")
                        },
                        new
                        {
                            CityId = new Guid("7f9ee2c3-5011-42de-9208-f5bb0cc1ccd7"),
                            CityName = "Dindigul",
                            StateId = new Guid("fab9319b-19ce-4029-a86e-7517eecba3dd")
                        },
                        new
                        {
                            CityId = new Guid("19cef82d-1739-4df3-8ce5-7f4936476f0b"),
                            CityName = "Hyderabad",
                            StateId = new Guid("b6886c43-1545-4ac8-b441-68bfe6e619ad")
                        },
                        new
                        {
                            CityId = new Guid("04bc4e06-1446-4aab-b93b-0cc2f8d6323d"),
                            CityName = "Warangal",
                            StateId = new Guid("b6886c43-1545-4ac8-b441-68bfe6e619ad")
                        },
                        new
                        {
                            CityId = new Guid("0c1775e5-75fd-43c9-9b13-234f376a24de"),
                            CityName = "Nizamabad",
                            StateId = new Guid("b6886c43-1545-4ac8-b441-68bfe6e619ad")
                        },
                        new
                        {
                            CityId = new Guid("521dd075-64e1-4ea4-be0c-86f17b8a35df"),
                            CityName = "Karimnagar",
                            StateId = new Guid("b6886c43-1545-4ac8-b441-68bfe6e619ad")
                        },
                        new
                        {
                            CityId = new Guid("d61996a1-a14c-467e-a789-bcdd8d07dace"),
                            CityName = "Khammam",
                            StateId = new Guid("b6886c43-1545-4ac8-b441-68bfe6e619ad")
                        },
                        new
                        {
                            CityId = new Guid("9cd71183-2df7-4fb9-a1ea-a5d45d2410b4"),
                            CityName = "Mahbubnagar",
                            StateId = new Guid("b6886c43-1545-4ac8-b441-68bfe6e619ad")
                        },
                        new
                        {
                            CityId = new Guid("ddadc997-4328-4636-bf10-f6dc407f8951"),
                            CityName = "Ramagundam",
                            StateId = new Guid("b6886c43-1545-4ac8-b441-68bfe6e619ad")
                        },
                        new
                        {
                            CityId = new Guid("cdd62457-eb64-4842-a654-79105f58f83b"),
                            CityName = "Adilabad",
                            StateId = new Guid("b6886c43-1545-4ac8-b441-68bfe6e619ad")
                        },
                        new
                        {
                            CityId = new Guid("abda0494-1f1b-4e08-9baf-e4bf37ba96c1"),
                            CityName = "Siddipet",
                            StateId = new Guid("b6886c43-1545-4ac8-b441-68bfe6e619ad")
                        },
                        new
                        {
                            CityId = new Guid("0881dcb9-7347-42fb-b756-6fca6f7c0aef"),
                            CityName = "Mancherial",
                            StateId = new Guid("b6886c43-1545-4ac8-b441-68bfe6e619ad")
                        },
                        new
                        {
                            CityId = new Guid("4fbec692-4a76-4e89-825c-b4dd24dfdd35"),
                            CityName = "Lucknow",
                            StateId = new Guid("e8e16639-e44f-4974-a965-ddfde1611388")
                        },
                        new
                        {
                            CityId = new Guid("e183cbd4-8fb7-4458-b7dd-a5948263e2e0"),
                            CityName = "Kanpur",
                            StateId = new Guid("e8e16639-e44f-4974-a965-ddfde1611388")
                        },
                        new
                        {
                            CityId = new Guid("5e8f2d40-b31f-40ba-9b9a-bdf33669cb92"),
                            CityName = "Varanasi",
                            StateId = new Guid("e8e16639-e44f-4974-a965-ddfde1611388")
                        },
                        new
                        {
                            CityId = new Guid("fb4f6c9b-0149-4d02-a9d5-9103d983b84e"),
                            CityName = "Agra",
                            StateId = new Guid("e8e16639-e44f-4974-a965-ddfde1611388")
                        },
                        new
                        {
                            CityId = new Guid("19301142-3791-40df-a621-e2e899aedaff"),
                            CityName = "Meerut",
                            StateId = new Guid("e8e16639-e44f-4974-a965-ddfde1611388")
                        },
                        new
                        {
                            CityId = new Guid("b5e40a31-e9fc-47f6-b4db-ba997a21caeb"),
                            CityName = "Allahabad",
                            StateId = new Guid("e8e16639-e44f-4974-a965-ddfde1611388")
                        },
                        new
                        {
                            CityId = new Guid("3c61aa54-baf4-4c95-8aeb-44bceee315e6"),
                            CityName = "Ghaziabad",
                            StateId = new Guid("e8e16639-e44f-4974-a965-ddfde1611388")
                        },
                        new
                        {
                            CityId = new Guid("b815eb60-515c-4828-948a-61582e366e2a"),
                            CityName = "Bareilly",
                            StateId = new Guid("e8e16639-e44f-4974-a965-ddfde1611388")
                        },
                        new
                        {
                            CityId = new Guid("ec6ff146-cdfc-4da2-9d81-82b9a8738265"),
                            CityName = "Aligarh",
                            StateId = new Guid("e8e16639-e44f-4974-a965-ddfde1611388")
                        },
                        new
                        {
                            CityId = new Guid("0417815c-7ccf-4f2a-9e91-edb4c297e746"),
                            CityName = "Moradabad",
                            StateId = new Guid("e8e16639-e44f-4974-a965-ddfde1611388")
                        },
                        new
                        {
                            CityId = new Guid("d0b6773d-c8f9-46b7-858f-a3a3023517d7"),
                            CityName = "Kolkata",
                            StateId = new Guid("f438e5e8-1802-48a9-9d01-d4dd249eb5d1")
                        },
                        new
                        {
                            CityId = new Guid("b66c7ff0-0e8f-405c-916c-21fb144a6531"),
                            CityName = "Howrah",
                            StateId = new Guid("f438e5e8-1802-48a9-9d01-d4dd249eb5d1")
                        },
                        new
                        {
                            CityId = new Guid("0d7047f0-ff40-45be-80f6-b7dce988d494"),
                            CityName = "Darjeeling",
                            StateId = new Guid("f438e5e8-1802-48a9-9d01-d4dd249eb5d1")
                        },
                        new
                        {
                            CityId = new Guid("52d2e8db-1737-4f74-ab30-b66bf76476d9"),
                            CityName = "Siliguri",
                            StateId = new Guid("f438e5e8-1802-48a9-9d01-d4dd249eb5d1")
                        },
                        new
                        {
                            CityId = new Guid("95fa4b5b-e915-4dbd-bf1f-dbc521c07646"),
                            CityName = "Durgapur",
                            StateId = new Guid("f438e5e8-1802-48a9-9d01-d4dd249eb5d1")
                        },
                        new
                        {
                            CityId = new Guid("f7bccc25-0d45-487b-9362-b6cf9e0152e8"),
                            CityName = "Asansol",
                            StateId = new Guid("f438e5e8-1802-48a9-9d01-d4dd249eb5d1")
                        },
                        new
                        {
                            CityId = new Guid("1585f1ef-5d22-42db-ad2c-0e393282a1be"),
                            CityName = "Malda",
                            StateId = new Guid("f438e5e8-1802-48a9-9d01-d4dd249eb5d1")
                        },
                        new
                        {
                            CityId = new Guid("835cddfb-0828-47d7-ad1a-32e321e67fde"),
                            CityName = "Bardhaman",
                            StateId = new Guid("f438e5e8-1802-48a9-9d01-d4dd249eb5d1")
                        },
                        new
                        {
                            CityId = new Guid("c0038929-3a16-45f8-9be1-67d03def1220"),
                            CityName = "Jalpaiguri",
                            StateId = new Guid("f438e5e8-1802-48a9-9d01-d4dd249eb5d1")
                        },
                        new
                        {
                            CityId = new Guid("a75292ca-947a-4d19-abdb-4b446591ef6e"),
                            CityName = "Haldia",
                            StateId = new Guid("f438e5e8-1802-48a9-9d01-d4dd249eb5d1")
                        });
                });

            modelBuilder.Entity("InsurancePolicy.Models.Claim", b =>
                {
                    b.Property<Guid>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankIFSCCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<double>("ClaimAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ClaimId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nominee")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomineeRelation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerId");

                    b.HasIndex("AgentId");

                    b.HasIndex("UserId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Document", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DocumentName")
                        .HasMaxLength(250)
                        .HasColumnType("int");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmployeeFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeId");

                    b.HasIndex("UserId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("InsurancePolicy.Models.InsurancePlan", b =>
                {
                    b.Property<Guid>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PlanId");

                    b.ToTable("InsurancePlans");
                });

            modelBuilder.Entity("InsurancePolicy.Models.InsuranceScheme", b =>
                {
                    b.Property<Guid>("SchemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("SchemeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("SchemeId");

                    b.ToTable("InsuranceSchemes");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<double>("AmountPaid")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Tax")
                        .HasColumnType("float");

                    b.Property<double>("TotalPayment")
                        .HasColumnType("float");

                    b.Property<int>("paymentType")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Policy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<Guid>("InsuranceSchemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("MaturityDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("PremiumAmount")
                        .HasColumnType("float");

                    b.Property<int>("PremiumType")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<double>("SumAssured")
                        .HasColumnType("float");

                    b.HasKey("PolicyId");

                    b.HasIndex("InsuranceSchemeId");

                    b.ToTable("InsurancePolicies");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7291d046-6694-4e06-978c-4d225f6704ba"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("d2e65388-63cf-4e0e-a5e1-8a895d4515df"),
                            Name = "Agent"
                        },
                        new
                        {
                            Id = new Guid("3f1f49fc-4f3a-4afc-ac82-d698482833f2"),
                            Name = "Employee"
                        },
                        new
                        {
                            Id = new Guid("762b45c3-0caf-455a-976b-c8e89b065837"),
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("InsurancePolicy.Models.SchemeDetails", b =>
                {
                    b.Property<Guid>("DetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double>("InstallmentCommRatio")
                        .HasColumnType("float");

                    b.Property<Guid>("InsuranceSchemeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<double>("MaxAmount")
                        .HasColumnType("float");

                    b.Property<int>("MaxInvestTime")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<double>("MinAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinInvestTime")
                        .HasColumnType("int");

                    b.Property<double>("ProfitRatio")
                        .HasColumnType("float");

                    b.Property<double>("RegistrationCommRatio")
                        .HasColumnType("float");

                    b.Property<string>("SchemeImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetailId");

                    b.HasIndex("InsuranceSchemeId")
                        .IsUnique();

                    b.ToTable("SchemeDetails");
                });

            modelBuilder.Entity("InsurancePolicy.Models.State", b =>
                {
                    b.Property<Guid>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = new Guid("ff790283-a7dd-4db6-9d17-5b287c4dc2ef"),
                            StateName = "Andhra Pradesh"
                        },
                        new
                        {
                            StateId = new Guid("ca59345f-670d-4536-8b5e-a71b581faad9"),
                            StateName = "Arunachal Pradesh"
                        },
                        new
                        {
                            StateId = new Guid("76acffda-92b2-4fdc-b8cc-3eb78281e1fc"),
                            StateName = "Assam"
                        },
                        new
                        {
                            StateId = new Guid("700b8d6b-ace2-4d89-8eb6-35ae1009a7f3"),
                            StateName = "Bihar"
                        },
                        new
                        {
                            StateId = new Guid("45d6dac4-356d-412c-9290-720ac52cec06"),
                            StateName = "Chhattisgarh"
                        },
                        new
                        {
                            StateId = new Guid("aa9dfba4-af52-4b09-b3ee-bcd036bdc245"),
                            StateName = "Goa"
                        },
                        new
                        {
                            StateId = new Guid("60e8c0fe-f916-4917-94ad-5a486d5703a4"),
                            StateName = "Gujarat"
                        },
                        new
                        {
                            StateId = new Guid("ad61f74f-efa5-41f5-bb98-5ca0d89778c8"),
                            StateName = "Haryana"
                        },
                        new
                        {
                            StateId = new Guid("ef4f21a3-110b-4826-8e48-4cebfea255b2"),
                            StateName = "Himachal Pradesh"
                        },
                        new
                        {
                            StateId = new Guid("8c9c47ad-b2ed-46fc-abe7-16948ab15a0a"),
                            StateName = "Jharkhand"
                        },
                        new
                        {
                            StateId = new Guid("4df48888-8202-446b-a3d9-d51174a53738"),
                            StateName = "Karnataka"
                        },
                        new
                        {
                            StateId = new Guid("6cd8dcf5-c85c-4fd7-bba8-fc28fcc4852d"),
                            StateName = "Kerala"
                        },
                        new
                        {
                            StateId = new Guid("d8bfef23-508d-4c5b-acc1-b4388b39bc7b"),
                            StateName = "Madhya Pradesh"
                        },
                        new
                        {
                            StateId = new Guid("e12f6cad-eed1-4d26-a17c-737afe19c94f"),
                            StateName = "Maharashtra"
                        },
                        new
                        {
                            StateId = new Guid("42a9c32c-b6cd-40b2-b0aa-be58b5ed4447"),
                            StateName = "Manipur"
                        },
                        new
                        {
                            StateId = new Guid("7bb77a43-3de8-4a1b-854e-7f23eece775b"),
                            StateName = "Meghalaya"
                        },
                        new
                        {
                            StateId = new Guid("bd54957c-74c8-42e8-8625-4c851f4d5355"),
                            StateName = "Mizoram"
                        },
                        new
                        {
                            StateId = new Guid("077d1d42-56a0-4527-add0-bcd332cef7d4"),
                            StateName = "Nagaland"
                        },
                        new
                        {
                            StateId = new Guid("33694ddb-5250-485b-ad64-f43f8006f0fc"),
                            StateName = "Odisha"
                        },
                        new
                        {
                            StateId = new Guid("23ca4ab2-2792-41e1-843c-0b9d349b500e"),
                            StateName = "Punjab"
                        },
                        new
                        {
                            StateId = new Guid("4f5b2aa8-9cc6-4046-bc15-c808010b52d8"),
                            StateName = "Rajasthan"
                        },
                        new
                        {
                            StateId = new Guid("2e9b9629-6dc1-4c93-ab8d-671d5b34867f"),
                            StateName = "Sikkim"
                        },
                        new
                        {
                            StateId = new Guid("fab9319b-19ce-4029-a86e-7517eecba3dd"),
                            StateName = "Tamil Nadu"
                        },
                        new
                        {
                            StateId = new Guid("b6886c43-1545-4ac8-b441-68bfe6e619ad"),
                            StateName = "Telangana"
                        },
                        new
                        {
                            StateId = new Guid("91787813-237f-498b-a47e-cc26066337c1"),
                            StateName = "Tripura"
                        },
                        new
                        {
                            StateId = new Guid("e8e16639-e44f-4974-a965-ddfde1611388"),
                            StateName = "Uttar Pradesh"
                        },
                        new
                        {
                            StateId = new Guid("1a5fd8f5-8c02-4b77-83d6-f7e9af50db08"),
                            StateName = "Uttarakhand"
                        },
                        new
                        {
                            StateId = new Guid("f438e5e8-1802-48a9-9d01-d4dd249eb5d1"),
                            StateName = "West Bengal"
                        });
                });

            modelBuilder.Entity("InsurancePolicy.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PaymentPolicy", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PoliciesPolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PaymentId", "PoliciesPolicyId");

                    b.HasIndex("PoliciesPolicyId");

                    b.ToTable("PaymentPolicy");
                });

            modelBuilder.Entity("CustomerPolicy", b =>
                {
                    b.HasOne("InsurancePolicy.Models.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsurancePolicy.Models.Policy", null)
                        .WithMany()
                        .HasForeignKey("PoliciesPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsurancePlanInsuranceScheme", b =>
                {
                    b.HasOne("InsurancePolicy.Models.InsurancePlan", null)
                        .WithMany()
                        .HasForeignKey("PlansPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsurancePolicy.Models.InsuranceScheme", null)
                        .WithMany()
                        .HasForeignKey("SchemesSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsurancePolicy.Models.Admin", b =>
                {
                    b.HasOne("InsurancePolicy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Agent", b =>
                {
                    b.HasOne("InsurancePolicy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsurancePolicy.Models.City", b =>
                {
                    b.HasOne("InsurancePolicy.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Claim", b =>
                {
                    b.HasOne("InsurancePolicy.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsurancePolicy.Models.Policy", "Policy")
                        .WithMany("Claim")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Customer", b =>
                {
                    b.HasOne("InsurancePolicy.Models.Agent", "Agent")
                        .WithMany("Customers")
                        .HasForeignKey("AgentId");

                    b.HasOne("InsurancePolicy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Agent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Document", b =>
                {
                    b.HasOne("InsurancePolicy.Models.Customer", "Customer")
                        .WithMany("Documents")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Employee", b =>
                {
                    b.HasOne("InsurancePolicy.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Policy", b =>
                {
                    b.HasOne("InsurancePolicy.Models.InsuranceScheme", "InsuranceScheme")
                        .WithMany("Policies")
                        .HasForeignKey("InsuranceSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsuranceScheme");
                });

            modelBuilder.Entity("InsurancePolicy.Models.SchemeDetails", b =>
                {
                    b.HasOne("InsurancePolicy.Models.InsuranceScheme", "InsuranceScheme")
                        .WithOne("SchemeDetails")
                        .HasForeignKey("InsurancePolicy.Models.SchemeDetails", "InsuranceSchemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsuranceScheme");
                });

            modelBuilder.Entity("InsurancePolicy.Models.User", b =>
                {
                    b.HasOne("InsurancePolicy.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PaymentPolicy", b =>
                {
                    b.HasOne("InsurancePolicy.Models.Payment", null)
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InsurancePolicy.Models.Policy", null)
                        .WithMany()
                        .HasForeignKey("PoliciesPolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsurancePolicy.Models.Agent", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Customer", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("InsurancePolicy.Models.InsuranceScheme", b =>
                {
                    b.Navigation("Policies");

                    b.Navigation("SchemeDetails");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Policy", b =>
                {
                    b.Navigation("Claim");
                });

            modelBuilder.Entity("InsurancePolicy.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("InsurancePolicy.Models.State", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
